export const SHORT_URL_REQUEST = 'SHORT_URL_REQUEST';
export const SHORT_URL_SUCCESS = 'SHORT_URL_SUCCESS';
export const SHORT_URL_FAILURE = 'SHORT_URL_FAILURE';


export const GET_OG_URL_REQUEST = 'GET_OG_URL_REQUEST';
export const GET_OG_URL_SUCCESS = 'GET_OG_URL_SUCCESS';
export const GET_OG_URL_FAILURE = 'GET_OG_URL_FAILURE';
